// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkI12FjBfLj9bQ5qJFKbe3nBv1sq0P5IE',
    appId: '1:846317614778:web:28ac57f333bb7809dfb483',
    messagingSenderId: '846317614778',
    projectId: 'my-notes-29550',
    authDomain: 'my-notes-29550.firebaseapp.com',
    storageBucket: 'my-notes-29550.appspot.com',
    measurementId: 'G-RLGHX8CLZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9aWMNKplFxNBrWpRVU7g7dHI57u9XbBQ',
    appId: '1:846317614778:android:1490791f6b279220dfb483',
    messagingSenderId: '846317614778',
    projectId: 'my-notes-29550',
    storageBucket: 'my-notes-29550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ToOCYkSZr-8QSb7YN83jlTq3QCYHPNY',
    appId: '1:846317614778:ios:dd8414998806a02fdfb483',
    messagingSenderId: '846317614778',
    projectId: 'my-notes-29550',
    storageBucket: 'my-notes-29550.appspot.com',
    iosClientId: '846317614778-0g0it1vqdka6s0l3tqm7l0l128pej2vd.apps.googleusercontent.com',
    iosBundleId: 'com.soyarturo.mynotes',
  );
}
